Repository IDLE-Sparta/order-management-server, pull requests merged in 2024-11, with the labels that each got.

#2 [#1] 프로젝트 디렉토리 구조 및 샘플 코드 작성
  .gitattributes
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sparta/ordermanagement/OrderManagementApplication.java
  src/main/java/com/sparta/ordermanagement/application/domain/Test.java
  src/main/java/com/sparta/ordermanagement/application/output/TestOutputPort.java
  src/main/java/com/sparta/ordermanagement/application/service/TestService.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/TestController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/TestRequestDto.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/TestResponseDto.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/exceptions/ErrorCode.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/exceptions/GlobalErrorCode.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/response/ApiResponse.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/TestAdapter.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/TestEntity.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/repository/TestRepository.java
  src/main/resources/application.yml
  src/test/java/com/sparta/ordermanagement/OrderManagementApplicationTests.java
Labels: setting

#20 [#18] QueryDSL 설정 파일 생성 완료
  build.gradle
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/ShopQueryController.java
  src/main/java/com/sparta/ordermanagement/framework/config/QueryDslConfig.java
Labels: setting

#21 [#14] 상품 등록, 상품 상태 변경, 상품 삭제 기능 구현 완료
  src/main/java/com/sparta/ordermanagement/application/domain/product/Product.java
  src/main/java/com/sparta/ordermanagement/application/domain/product/ProductForCreate.java
  src/main/java/com/sparta/ordermanagement/application/domain/product/ProductForDelete.java
  src/main/java/com/sparta/ordermanagement/application/domain/product/ProductStateForUpdate.java
  src/main/java/com/sparta/ordermanagement/application/exception/DeletedException.java
  src/main/java/com/sparta/ordermanagement/application/exception/ForbiddenException.java
  src/main/java/com/sparta/ordermanagement/application/exception/message/ProductErrorMessage.java
  src/main/java/com/sparta/ordermanagement/application/exception/message/ShopErrorMessage.java
  src/main/java/com/sparta/ordermanagement/application/exception/product/ProductDeletedException.java
  src/main/java/com/sparta/ordermanagement/application/exception/product/ProductNotBelongToShopException.java
  src/main/java/com/sparta/ordermanagement/application/exception/product/ProductUuidInvalidException.java
  src/main/java/com/sparta/ordermanagement/application/exception/shop/ShopUuidInvalidException.java
  src/main/java/com/sparta/ordermanagement/application/output/ProductOutputPort.java
  src/main/java/com/sparta/ordermanagement/application/output/ShopOutputPort.java
  src/main/java/com/sparta/ordermanagement/application/service/ProductService.java
  src/main/java/com/sparta/ordermanagement/application/service/ShopService.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/ProductCommandController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/product/ProductCreateRequest.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/product/ProductCreateResponse.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/product/ProductDeleteResponse.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/product/ProductStateUpdateRequest.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/product/ProductStateUpdateResponse.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/ProductPersistenceAdapter.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/ShopPersistenceAdapter.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/BaseEntity.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/product/ProductEntity.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/repository/ProductRepository.java
Labels: implement

#27 [#15] 가게 상품 조회 기능 구현 완료
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/ProductCommandController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/ProductQueryController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/product/ProductCreateRequest.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/product/ProductListResponse.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/ProductPersistenceAdapter.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/product/ProductEntity.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/repository/ProductQueryRepository.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/vo/ProductSort.java
Labels: implement

#30 가게 키워드 검색 기능에서 페이징 처리 이후 정렬되는 문제 해결
  src/main/java/com/sparta/ordermanagement/framework/persistence/repository/ShopQueryRepository.java
Labels: bug, modify

#37 [#36] 관리자 가게 정보 등록, 수정 삭제 기능 구현
  src/main/java/com/sparta/ordermanagement/application/admin/AdminShopCategoryService.java
  src/main/java/com/sparta/ordermanagement/application/admin/AdminShopService.java
  src/main/java/com/sparta/ordermanagement/application/admin/vo/ShopForCreate.java
  src/main/java/com/sparta/ordermanagement/application/output/ShopOutputPort.java
  src/main/java/com/sparta/ordermanagement/application/service/ShopService.java
  src/main/java/com/sparta/ordermanagement/bootstrap/admin/controller/AdminShopController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/admin/dto/ShopCreateRequest.java
  src/main/java/com/sparta/ordermanagement/bootstrap/admin/dto/ShopUpdateRequest.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/ShopCommandController.java
  src/main/java/com/sparta/ordermanagement/framework/admin/repository/AdminShopCategoryRepository.java
  src/main/java/com/sparta/ordermanagement/framework/admin/repository/AdminShopRepository.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/ShopPersistenceAdapter.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/shop/ShopEntity.java
Labels: implement

#40 [#38] 브랜치 생성 시기에 따라 코드 병합 시 발생하는 문제 해결
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/shop/ShopEntity.java
  src/main/resources/application.yml
Labels: bug, modify

#39 [#19] 사용자 인증 기능 구현
  build.gradle
  src/main/java/com/sparta/ordermanagement/application/domain/user/User.java
  src/main/java/com/sparta/ordermanagement/application/domain/user/UserForSignin.java
  src/main/java/com/sparta/ordermanagement/application/domain/user/UserForSignup.java
  src/main/java/com/sparta/ordermanagement/application/output/UserOutputPort.java
  src/main/java/com/sparta/ordermanagement/application/service/UserService.java
  src/main/java/com/sparta/ordermanagement/bootstrap/auth/UserDetailsImpl.java
  src/main/java/com/sparta/ordermanagement/bootstrap/config/SecurityConfig.java
  src/main/java/com/sparta/ordermanagement/bootstrap/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/UserCommandController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/user/UserSecurityInfo.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/user/UserSigninRequest.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/user/UserSignupRequest.java
  src/main/java/com/sparta/ordermanagement/bootstrap/util/JwtUtil.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/UserPersistenceAdapter.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/order/OrderEntity.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/user/UserEntity.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/repository/UserRepository.java
  src/main/resources/application.yml
Labels: implement

#43 [#32] 주문 상태 및 주문 상품 수정 기능 구현
  src/main/java/com/sparta/ordermanagement/application/domain/order/Order.java
  src/main/java/com/sparta/ordermanagement/application/domain/order/OrderForCreate.java
  src/main/java/com/sparta/ordermanagement/application/domain/order/OrderForUpdate.java
  src/main/java/com/sparta/ordermanagement/application/domain/order/OrderState.java
  src/main/java/com/sparta/ordermanagement/application/exception/message/OrderErrorMessage.java
  src/main/java/com/sparta/ordermanagement/application/exception/order/InvalidOrderException.java
  src/main/java/com/sparta/ordermanagement/application/exception/order/OrderCancellationTimeExceededException.java
  src/main/java/com/sparta/ordermanagement/application/exception/order/OrderStateChangedException.java
  src/main/java/com/sparta/ordermanagement/application/exception/order/OrderStateInvalidException.java
  src/main/java/com/sparta/ordermanagement/application/output/OrderOutputPort.java
  src/main/java/com/sparta/ordermanagement/application/service/OrderService.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/OrderCommandController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/order/OrderCreateRequest.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/dto/order/OrderUpdateRequest.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/OrderPersistenceAdapter.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/order/OrderEntity.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/order/OrderState.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/repository/OrderRepository.java
Labels: implement

#46 [#45] 유저 전체 조회 기능 구현
  src/main/java/com/sparta/ordermanagement/application/admin/AdminUserService.java
  src/main/java/com/sparta/ordermanagement/application/output/UserOutputPort.java
  src/main/java/com/sparta/ordermanagement/bootstrap/admin/controller/AdminUserController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/admin/dto/UserGetResponse.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/UserPersistenceAdapter.java
Labels: implement

#55 [#47] 로그인 및 유저 기능 추가에 따른 shop 로직 수정
  build.gradle
  src/main/java/com/sparta/ordermanagement/application/admin/AdminShopService.java
  src/main/java/com/sparta/ordermanagement/application/domain/shop/Shop.java
  src/main/java/com/sparta/ordermanagement/application/exception/message/ShopErrorMessage.java
  src/main/java/com/sparta/ordermanagement/application/exception/shop/ShopOwnerMismatchException.java
  src/main/java/com/sparta/ordermanagement/application/output/ShopOutputPort.java
  src/main/java/com/sparta/ordermanagement/application/service/ShopService.java
  src/main/java/com/sparta/ordermanagement/application/service/UserService.java
  src/main/java/com/sparta/ordermanagement/bootstrap/admin/controller/AdminShopController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/admin/dto/ShopListResponse.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/ShopCommandController.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/adapter/ShopPersistenceAdapter.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/entity/shop/ShopEntity.java
  src/main/java/com/sparta/ordermanagement/framework/persistence/repository/ShopQueryRepository.java
Labels: implement

#84 [#82] User API 리펙토링
  src/main/java/com/sparta/ordermanagement/application/admin/AdminUserService.java
  src/main/java/com/sparta/ordermanagement/application/exception/user/UserAuthenticationException.java
  src/main/java/com/sparta/ordermanagement/application/service/AiService.java
  src/main/java/com/sparta/ordermanagement/application/service/UserService.java
  src/main/java/com/sparta/ordermanagement/bootstrap/admin/controller/AdminUserController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/AiController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/UserCommandController.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/exceptions/ForbiddenActionException.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/exception/exceptions/RequestValidationException.java
Labels: refactor

#90 [#89] JWT 하나의 엔드포인트에서 HTTP 메소드별 필터링 처리 구현
  src/main/java/com/sparta/ordermanagement/bootstrap/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/ordermanagement/bootstrap/rest/controller/ProductQueryController.java
Labels: bug, implement

#96 [#95] 배포를 위한 환경 설정 파일 작성
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/resources/application-deploy.yml
Labels: setting

#99 [#98] 프로젝트 시작 방법 추가
  README.md
Labels: documentation

#103 [#102] db 관리를 위한 pgAdmin 추가
  docker-compose.yml
Labels: setting
